version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: brainwaves
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    command: python app.py

  postgres:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: brainwaves
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

volumes:
  pgdata: